
CREATE TABLE ACCOUNT_USER (
  ID     BIGINT PRIMARY KEY,
  LOGIN_NAME   VARCHAR(255) NOT NULL UNIQUE,
  STATUS VARCHAR(10),
  
  UPDATED_AT  date,
  UPDATED_BY  VARCHAR(255),
  NOTES       VARCHAR(255),
  CREATED_AT  date,
  CREATED_BY  VARCHAR(255)
);

CREATE SEQUENCE public.account_user_seq INCREMENT 1 START 1 MINVALUE 1;


create table ACCOUNT_TYPE(
  ID     BIGINT PRIMARY KEY,
  NAME   varchar(10),
  DESCRIPTION varchar(255),
  STATUS varchar(10),
  
  UPDATED_AT  date,
  UPDATED_BY  VARCHAR(255),
  NOTES       VARCHAR(255),
  CREATED_AT  date,
  CREATED_BY  VARCHAR(255)
);

CREATE SEQUENCE account_type_seq INCREMENT 1 START 1 MINVALUE 1;

create table ACCOUNT(
	ID     BIGINT PRIMARY KEY,
	ACCOUNT_USER_ID BIGINT REFERENCES ACCOUNT_USER,
	ACCOUNT_NUMBER BIGINT unique,
	ACCOUNT_NAME VARCHAR(20),
	ACCOUNT_TYPE_ID BIGINT REFERENCES ACCOUNT_TYPE,
	BALANCE_DATE date,
	CURRENCY VARCHAR(4),
	BALANCE Float(2),
	
  UPDATED_AT  date,
  UPDATED_BY  VARCHAR(255),
  NOTES       VARCHAR(255),
  CREATED_AT  date,
  CREATED_BY  VARCHAR(255)
);

CREATE SEQUENCE account_seq INCREMENT 1 START 1 MINVALUE 1;

create table TRANSACTION_TYPE(
  ID     BIGINT PRIMARY KEY,
  NAME   VARCHAR(10),
  DESCRIPTION VARCHAR(255),
  STATUS VARCHAR(10),
  
  UPDATED_AT  date,
  UPDATED_BY  VARCHAR(255),
  NOTES       VARCHAR(255),
  CREATED_AT  date,
  CREATED_BY  VARCHAR(255)
);

CREATE SEQUENCE transaction_type_seq INCREMENT 1 START 1 MINVALUE 1;

create table ACCOUNT_TRANSACTION(
	ID     BIGINT PRIMARY KEY,
	ACCOUNT_ID BIGINT REFERENCES account,
	VALUE_DATE date,
	DEBIT_AMOUNT Float(2),
	CREDIT_AMOUNT Float(2),
	TRANSACTION_TYPE_ID BIGINT REFERENCES transaction_type,
	NARRATIVE varchar(255),
	
  UPDATED_AT  date,
  UPDATED_BY  VARCHAR(255),
  NOTES       VARCHAR(255),
  CREATED_AT  date,
  CREATED_BY  VARCHAR(255)
);

CREATE SEQUENCE account_transaction_seq INCREMENT 1 START 1 MINVALUE 1;
